name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Ruff (lint)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy factchecker

      - name: Run tests + coverage
        run: |
          pytest -q --cov=factchecker --cov-report=term-missing
